// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35HSvKCvKy4ecWKvP7h4P_SqPMzYtVjY',
    appId: '1:237921166775:web:e3b0da74b82e5e2cd5f432',
    messagingSenderId: '237921166775',
    projectId: 'easeflow-f1130',
    authDomain: 'easeflow-f1130.firebaseapp.com',
    storageBucket: 'easeflow-f1130.firebasestorage.app',
    measurementId: 'G-SCLTPX6VXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTbJlRQOlMgD7i0FWJRvacUQSS3QwFH8',
    appId: '1:237921166775:android:6ae7e67cf2433287d5f432',
    messagingSenderId: '237921166775',
    projectId: 'easeflow-f1130',
    storageBucket: 'easeflow-f1130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcSLWwBDPwrusLGVu24eTNstQifgfCpk',
    appId: '1:237921166775:ios:aa61baee3e23afbed5f432',
    messagingSenderId: '237921166775',
    projectId: 'easeflow-f1130',
    storageBucket: 'easeflow-f1130.firebasestorage.app',
    iosBundleId: 'com.example.easeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgcSLWwBDPwrusLGVu24eTNstQifgfCpk',
    appId: '1:237921166775:ios:aa61baee3e23afbed5f432',
    messagingSenderId: '237921166775',
    projectId: 'easeflow-f1130',
    storageBucket: 'easeflow-f1130.firebasestorage.app',
    iosBundleId: 'com.example.easeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC35HSvKCvKy4ecWKvP7h4P_SqPMzYtVjY',
    appId: '1:237921166775:web:c52fd234ec006003d5f432',
    messagingSenderId: '237921166775',
    projectId: 'easeflow-f1130',
    authDomain: 'easeflow-f1130.firebaseapp.com',
    storageBucket: 'easeflow-f1130.firebasestorage.app',
    measurementId: 'G-CDYSHTLRD5',
  );
}
